spring:
  application:
    name: logging-starter
http-logging:
  configuration:
    enabled: true
    log-level: info
    time-request-parameter: startTime
    log-format: '%n%M %u %nHeaders:%n%h%n%H%n%R %r %tms.'
